### ISSUE TITLE
Test scripts with "Process 3DS Enrollment" steps fail due to invalid 3DS_ID 

### ISSUE THREAD

**Issue by abarmp** [myNBGcode/E-commerceEnterprise#1]
In the postman samples with 3DS, the step used to process the 3DS paRes info fails because in the previous step the 3DS id has not been succesfully transfered to the 3DS_ID environment variable. The test script that runs after the execution of the "Check 3DS Enrollment" step fails due to invalid JS code.

Test script after "Check 3DS Enrollment" should succeed in transferring the 3DS id returned in the response so the subswquent steps do not fail.

**Comment by ABHILASHAB1** [comment]
Can i use the piece of good for building ACS 3DS simulator ?

Requesting your guidelines

**Comment by ABHILASHAB1** [comment]
you can reach me on abhilashmyself007@gmail.com .

Awaiting for your revert

**Comment by ckifonidis** [comment]
> Can i use the piece of good for building ACS 3DS simulator ?
> 
> Requesting your guidelines

Hi Abhilash,

Yes you can use any code in this repository.
